import type { PricingModelDefinition } from "./types";

const NS_MATCHES = "PremiumCricket.Lib.Pricing.PricingModels.PreMatch.Models.Matches";
const NS_PLAYERS = "PremiumCricket.Lib.Pricing.PricingModels.PreMatch.Models.Players";
const NS_HEADTOHEADS = "PremiumCricket.Lib.Pricing.PricingModels.PreMatch.Models.HeadToHeads";
const NS_TEAMS = "PremiumCricket.Lib.Pricing.PricingModels.PreMatch.Models.Teams";
const FILE_MATCHES = "reference/pricing-models/PreMatch/Models/Matches";
const FILE_PLAYERS = "reference/pricing-models/PreMatch/Models/Players";
const FILE_HEADTOHEADS = "reference/pricing-models/PreMatch/Models/HeadToHeads";
const FILE_TEAMS = "reference/pricing-models/PreMatch/Models/Teams";

export const additionalPricingModels: PricingModelDefinition[] = [
  {
    id: "tied-match",
    registryModelId: "pm-tied-match",
    className: "TiedMatch",
    namespace: NS_MATCHES,
    filePath: `${FILE_MATCHES}/TiedMatch.cs`,
    phase: "pre_match",
    marketName: "Tied Match",
    marketCode: "64PINB",
    marketId: 999,
    legacyMarketId: 41,
    description:
      "Yes/No tied match derived from match odds competitiveness. Delegates to MatchBetting for priceDiff.",
    inputs: [
      {
        name: "MatchOdds",
        label: "Match betting probabilities",
        scope: "parameter",
        csharpPath: "MatchBetting.GetMatchOdds(inputs)",
        excelRef: "Prep Work!C10:C11 / PM Publication!G20:G21",
        notes: "priceDiff = |0.5 - homeProb| × 2",
      },
      {
        name: "Format",
        label: "Match format",
        scope: "parameter",
        csharpPath: "inputs.Evaluation.MatchEvaluation.Format",
      },
      {
        name: "TiedMatch",
        label: "Tied match adjust",
        scope: "trading_input",
        csharpPath: "inputs.AdjustmentsPM.MatchAdjustments.TiedMatch",
        excelRef: "PM Publication!I22",
      },
    ],
    embeddedConstants: [
      { name: "T10Base", value: "0.02" },
      { name: "T20Base", value: "0.02 - 0.02 × priceDiff" },
      { name: "ODIBase", value: "0.013 - 0.01 × priceDiff" },
      { name: "TestDefault", value: "0.001" },
    ],
    outputs: [
      {
        name: "tiedYes",
        label: "Tied — Yes",
        type: "probability",
        excelRef: "PM Publication!G22 / PM Pricing!C4",
      },
      {
        name: "tiedNo",
        label: "Tied — No",
        type: "probability",
        excelRef: "PM Publication!G23",
      },
    ],
    missingForParity: [
      "Confirm PM Pricing vs PM Publication as canonical tied prob",
      "Test/FC uses 0.001 base — verify vs Excel for Test fixtures separately",
    ],
  },
  {
    id: "toss-win-double",
    registryModelId: "pm-toss-win-double",
    className: "TossWinDouble",
    namespace: NS_MATCHES,
    filePath: `${FILE_MATCHES}/TossWinDouble.cs`,
    phase: "pre_match",
    marketName: "Toss/Win Double",
    marketCode: "TWD",
    marketId: 999,
    legacyMarketId: 68,
    description:
      "Home/away toss-win combos plus no-winner outcome. Uses match odds and TossValue.",
    inputs: [
      {
        name: "MatchOdds",
        label: "Match betting probabilities",
        scope: "parameter",
        csharpPath: "MatchBetting.GetMatchOdds(inputs)",
        excelRef: "PM Publication!G20:G21",
      },
      {
        name: "TossValue",
        label: "Toss value",
        scope: "trading_input",
        csharpPath: "inputs.Evaluation.MatchEvaluation.TossValue",
        excelRef: "PM Publication!I26 (Toss value)",
        notes: "homeProb = matchHome×0.5 + tossValue",
      },
    ],
    embeddedConstants: [
      { name: "MatchOddsWeight", value: "0.5", notes: "Half match prob + toss skew" },
    ],
    outputs: [
      { name: "homeTossWin", label: "Home team", type: "probability", excelRef: "PM Publication!G26" },
      { name: "awayTossWin", label: "Away team", type: "probability", excelRef: "PM Publication!G27" },
      { name: "noWinner", label: "No winner / draw leg", type: "probability", excelRef: "PM Publication!G28" },
    ],
    missingForParity: [
      "TossValue Excel cell mapping beyond I26 label",
      "Pre-match TossValue when toss not taken",
    ],
  },
  {
    id: "player-runs",
    registryModelId: "pm-player-runs",
    className: "PlayerRuns",
    namespace: NS_PLAYERS,
    filePath: `${FILE_PLAYERS}/PlayerRuns.cs`,
    phase: "pre_match",
    marketName: "Player Runs",
    marketCode: "5{n}BARU / 6{n}BARU",
    marketId: 638,
    legacyMarketId: 4,
    description:
      "One under/over market per squad player. Extends PlayerScores base class. Test/FC renames to 1st Innings Runs.",
    inputs: [
      {
        name: "ExpectedRuns",
        label: "Player expected runs",
        scope: "parameter",
        csharpPath: "player.BatsmanEvaluation.ExpectedRuns",
        excelRef: "Prep Work Q-column player ratings → expected runs",
      },
      {
        name: "BatsmanRuns",
        label: "Batsman runs adjust",
        scope: "trading_input",
        csharpPath: "batterAdjustment.BatsmanRuns",
        excelRef: "PM Publication!I per player row (purple)",
        notes: "Added to rounded line",
      },
      {
        name: "RatioConstant",
        label: "Ratio constant by batting position",
        scope: "embedded",
        csharpPath: "GetRatioConstant(inputs, batPosition + indexAdjust)",
      },
    ],
    embeddedConstants: [
      { name: "LineFormula", value: "Round(ratioConstant × ExpectedRuns) + Round(BatsmanRuns)" },
      { name: "MarketCodePattern", value: "5/6 + batPosition + BARU" },
    ],
    outputs: [
      {
        name: "playerRunsLine",
        label: "Per-player run line",
        type: "line",
        notes: "One market per player — PM template Player - Runs",
      },
      {
        name: "underOver",
        label: "Under / Over 0.5",
        type: "outcome_set",
        csharpPath: "GetOverUnderOutcomes(0.5)",
      },
    ],
    missingForParity: [
      "PlayerScores base class (GetRatioConstant, GetSpecifiers)",
      "Map each player row in PM Publication to batterAdjustment",
      "BatterAdjustmentsPM structure",
    ],
  },
  {
    id: "match-top-batter",
    registryModelId: "pm-match-top-batter",
    className: "MatchTopBatter",
    namespace: NS_MATCHES,
    filePath: `${FILE_MATCHES}/MatchTopBatter.cs`,
    phase: "pre_match",
    marketName: "Match Top Bat",
    marketCode: "PMTRSNL",
    marketId: 683,
    legacyMarketId: 45,
    description:
      "Race distribution across all batters with Poisson-gamma run distributions and minimum probability floor.",
    inputs: [
      {
        name: "PlayerRuns",
        label: "Per-player run expectation",
        scope: "parameter",
        csharpPath: "TopBatterMethods.GetPlayerRuns(...)",
      },
      {
        name: "ConditionAdjustment",
        label: "Conditions",
        scope: "parameter",
        csharpPath: "inputs.Evaluation.MatchEvaluation.ConditionAdjustment",
        excelRef: "Prep Work!D3",
      },
      {
        name: "VarianceLookup",
        label: "PlayerRuns variance lookup",
        scope: "embedded",
        csharpPath: "GetVarianceParameters('PlayerRuns')",
      },
      {
        name: "ZeroProbLookup",
        label: "Zero probability lookup",
        scope: "embedded",
        csharpPath: "GetVarianceParameters('ZeroProb')",
      },
    ],
    embeddedConstants: [
      { name: "RaceDistributionCap", value: "500" },
      { name: "MinimumLookup", value: "GetMatchTopBatMinimumLookup by batting pos mod 11" },
    ],
    outputs: [
      {
        name: "topBatOutcomes",
        label: "Per-player top bat probability",
        type: "outcome_set",
        excelRef: "PM Publication — Match Top Bat. rows",
      },
    ],
    missingForParity: ["Exact PM Publication row range for match top bat"],
  },
  {
    id: "match-top-bowler",
    registryModelId: "pm-match-top-bowler",
    className: "MatchTopBowler",
    namespace: NS_MATCHES,
    filePath: `${FILE_MATCHES}/MatchTopBowler.cs`,
    phase: "pre_match",
    marketName: "Match Top Bowler",
    marketCode: "PMTWTNL",
    marketId: 684,
    legacyMarketId: 46,
    description:
      "Race distribution across bowlers using expected wickets and Poisson-gamma variance. Normalizes top 22 then appends extras.",
    inputs: [
      {
        name: "ExpectedWickets",
        label: "Bowler expected wickets",
        scope: "parameter",
        csharpPath: "BowlerEvaluation.GetExpectedWickets()",
      },
      {
        name: "BattingRating",
        label: "Opposition batting rating",
        scope: "parameter",
        csharpPath: "battingTeam.BattingRating",
        notes: "wicketAdjust = 0.5 × (batRating/conditions + 1)",
      },
      {
        name: "ConditionAdjustment",
        label: "Conditions",
        scope: "parameter",
        csharpPath: "inputs.Evaluation.MatchEvaluation.ConditionAdjustment",
        excelRef: "Prep Work!D3",
      },
    ],
    embeddedConstants: [
      { name: "RaceDistributionCap", value: "10" },
      { name: "MainSquadSize", value: "22", notes: "Normalized first, extras scaled by totalProb" },
      { name: "WicketAdjustFormula", value: "0.5 × (batRating/conditions + 1)" },
    ],
    outputs: [
      {
        name: "topBowlOutcomes",
        label: "Per-player top bowler probability",
        type: "outcome_set",
        excelRef: "PM Publication — Match Top Bowler. rows",
      },
    ],
    missingForParity: [
      "Player level adjustments (currently 0.00 placeholders)",
      "Exact PM Publication row range",
    ],
  },
  {
    id: "team-of-top-bat",
    registryModelId: "pm-team-of-top-bat",
    className: "TeamOfTopBat",
    namespace: NS_HEADTOHEADS,
    filePath: `${FILE_HEADTOHEADS}/TeamOfTopBat.cs`,
    phase: "pre_match",
    marketName: "Team of Top Bat",
    marketCode: "59BARUA",
    marketId: 698,
    legacyMarketId: 58,
    description:
      "Two-way market: which team supplies the match top batter. Derived from match odds via MatchBetting; spawns per-team TeamTopBatter markets.",
    inputs: [
      {
        name: "MatchOdds",
        label: "Match betting probabilities",
        scope: "parameter",
        csharpPath: "matchMarket.Outcomes",
        excelRef: "Prep Work!C10:C11 / PM Publication!G20:G21",
        notes: "Passed from parent MatchBetting.CreateMarket",
      },
      {
        name: "TeamOfTopBat",
        label: "Team of top bat adjust",
        scope: "trading_input",
        csharpPath: "inputs.AdjustmentsPM.MatchAdjustments.TeamOfTopBat",
        excelRef: "PM Publication!I60",
        notes: "Purple adjust — added as home prob skew (÷100)",
      },
    ],
    embeddedConstants: [
      { name: "HomeWeight", value: "0.86", notes: "Blend on match home prob" },
      { name: "AwayWeight", value: "0.14", notes: "Blend on match away prob" },
    ],
    outputs: [
      {
        name: "homeTeamTopBat",
        label: "Home team top bat",
        type: "probability",
        excelRef: "PM Publication!G60",
      },
      {
        name: "awayTeamTopBat",
        label: "Away team top bat",
        type: "probability",
        excelRef: "PM Publication!G61",
      },
    ],
    missingForParity: [
      "HeadStandardMarketPricingModel base class",
      "Confirm I60 adjust cell vs PM Publication layout",
      "Relationship to TeamTopBatter per-team markets",
    ],
  },
  {
    id: "team-of-top-bowl",
    registryModelId: "pm-team-of-top-bowl",
    className: "TeamOfTopBowl",
    namespace: NS_HEADTOHEADS,
    filePath: `${FILE_HEADTOHEADS}/TeamOfTopBowl.cs`,
    phase: "pre_match",
    marketName: "Team of Top Bowl",
    marketCode: "510BARUA",
    marketId: 699,
    legacyMarketId: 59,
    description:
      "Two-way market: which team supplies the match top bowler. Format-dependent blend from match odds; spawns per-team TeamTopBowler markets.",
    inputs: [
      {
        name: "MatchOdds",
        label: "Match betting probabilities",
        scope: "parameter",
        csharpPath: "matchMarket.Outcomes",
        excelRef: "Prep Work!C10:C11 / PM Publication!G20:G21",
      },
      {
        name: "Format",
        label: "Match format",
        scope: "parameter",
        csharpPath: "inputs.Evaluation.MatchEvaluation.IsT10 / IsT20",
        notes: "T10/T20 vs ODI/Test/FC blend coefficients",
      },
      {
        name: "TeamOfTopBowl",
        label: "Team of top bowl adjust",
        scope: "trading_input",
        csharpPath: "inputs.AdjustmentsPM.MatchAdjustments.TeamOfTopBowl",
        excelRef: "PM Publication!I62",
        notes: "Purple adjust — added as home prob skew (÷100)",
      },
    ],
    embeddedConstants: [
      { name: "T10T20HomeWeight", value: "0.74" },
      { name: "T10T20AwayWeight", value: "0.26" },
      { name: "LongFormHomeWeight", value: "0.83" },
      { name: "LongFormAwayWeight", value: "0.17" },
    ],
    outputs: [
      {
        name: "homeTeamTopBowl",
        label: "Home team top bowl",
        type: "probability",
        excelRef: "PM Publication!G62",
      },
      {
        name: "awayTeamTopBowl",
        label: "Away team top bowl",
        type: "probability",
        excelRef: "PM Publication!G63",
      },
    ],
    missingForParity: [
      "HeadStandardMarketPricingModel base class",
      "Confirm I62 adjust cell vs PM Publication layout",
      "T10 uses same blend as T20 in Lambda",
    ],
  },
  {
    id: "team-top-batter",
    registryModelId: "pm-team-top-batter",
    className: "TeamTopBatter",
    namespace: "PremiumCricket.Lib.Pricing.PricingModels.PreMatch.Models.Teams",
    filePath: "reference/pricing-models/PreMatch/Models/Teams/TeamTopBatter.cs",
    phase: "pre_match",
    marketName: "Top Bat (per team)",
    marketCode: "NL1TBNL / NL2TBNL",
    marketId: 674,
    legacyMarketId: 36,
    description:
      "Team top batter race — one market per team (home 674, away 675). Spawned from MatchBetting via TeamOfTopBat.",
    inputs: [
      {
        name: "PlayerRuns",
        label: "Per-player run expectation",
        scope: "parameter",
        csharpPath: "TopBatterMethods.GetPlayerRuns(...)",
      },
      {
        name: "ConditionAdjustment",
        label: "Conditions",
        scope: "parameter",
        csharpPath: "inputs.Evaluation.MatchEvaluation.ConditionAdjustment",
        excelRef: "Prep Work!D3",
      },
      {
        name: "VarianceLookup",
        label: "PlayerRuns variance",
        scope: "embedded",
        csharpPath: "GetVarianceParameters('PlayerRuns')",
      },
      {
        name: "ZeroProbLookup",
        label: "Zero probability lookup",
        scope: "embedded",
        csharpPath: "GetVarianceParameters('ZeroProb')",
      },
    ],
    embeddedConstants: [
      { name: "RaceDistributionCap", value: "500" },
      { name: "MinimumLookup", value: "GetTopBatMinimumLookup" },
      { name: "OutcomeEncoding", value: "PlayerName|PlayerId in category" },
    ],
    outputs: [
      {
        name: "teamTopBatOutcomes",
        label: "Per-player top bat prob (per team)",
        type: "outcome_set",
        excelRef: "PM Publication — {Team} - Top Bat",
      },
    ],
    missingForParity: ["PM row range per team top bat market"],
  },
  {
    id: "team-top-bowler",
    registryModelId: "pm-team-top-bowler",
    className: "TeamTopBowler",
    namespace: "PremiumCricket.Lib.Pricing.PricingModels.PreMatch.Models.Teams",
    filePath: "reference/pricing-models/PreMatch/Models/Teams/TeamTopBowler.cs",
    phase: "pre_match",
    marketName: "Top Bowl (per team)",
    marketCode: "NL1BBNL / NL2BBNL",
    marketId: 676,
    legacyMarketId: 37,
    description:
      "Team top bowler race — one market per team (home 676, away 677). Spawned from MatchBetting via TeamOfTopBowl.",
    inputs: [
      {
        name: "ExpectedWickets",
        label: "Bowler expected wickets",
        scope: "parameter",
        csharpPath: "BowlerEvaluation.GetExpectedWickets()",
      },
      {
        name: "OppositionBattingRating",
        label: "Opposition batting rating",
        scope: "parameter",
        csharpPath: "battingTeam.BattingRating",
        notes: "wicketAdjust = 0.5 × (batRating/conditions + 1)",
      },
      {
        name: "ConditionAdjustment",
        label: "Conditions",
        scope: "parameter",
        csharpPath: "inputs.Evaluation.MatchEvaluation.ConditionAdjustment",
        excelRef: "Prep Work!D3",
      },
    ],
    embeddedConstants: [
      { name: "RaceDistributionCap", value: "10" },
      { name: "MainSquadSize", value: "11", notes: "Normalize first 11, scale extras" },
      { name: "MinProbability", value: "T20=0.04, ODI=0.03, else 0.02" },
    ],
    outputs: [
      {
        name: "teamTopBowlOutcomes",
        label: "Per-player top bowl prob (per team)",
        type: "outcome_set",
        excelRef: "PM Publication — {Team} - Top Bowl",
      },
    ],
    missingForParity: [
      "Player adjusts currently 0.0",
      "PM row range per team top bowl market",
    ],
  },
  {
    id: "highest-individual-score",
    registryModelId: "pm-highest-individual-score",
    className: "HighestIndividualScore",
    namespace: NS_MATCHES,
    filePath: `${FILE_MATCHES}/HighestIndividualScore.cs`,
    phase: "pre_match",
    marketName: "Highest Individual Score",
    marketCode: "63BARUA",
    marketId: 702,
    legacyMarketId: 62,
    description:
      "Under/over on highest individual score. Line = Round(MatchHighScore) + trader adjust + 0.5. Fixed 0.5 prob split at market creation.",
    inputs: [
      {
        name: "MatchHighScore",
        label: "Match high score expectation",
        scope: "parameter",
        csharpPath: "inputs.Evaluation.MatchEvaluation.MatchHighScore",
        excelRef: "Prep Work — source cell TBD",
        notes: "Rounded to integer before line is set",
      },
      {
        name: "HighestIndividualScore",
        label: "Highest individual score adjust",
        scope: "trading_input",
        csharpPath: "inputs.AdjustmentsPM.MatchAdjustments.HighestIndividualScore",
        excelRef: "PM Publication!I75",
        notes: "Added directly to run line before +0.5",
      },
      {
        name: "OversAvailable",
        label: "Overs available",
        scope: "parameter",
        csharpPath: "inputs.MatchState.GetCurrentInnings().OversAvailable",
        notes: "MaxOverSpecifier on published market",
      },
    ],
    embeddedConstants: [
      { name: "LineOffset", value: "+0.5", notes: "LineSpecifier after Round(highScore) + adjust" },
      { name: "UnderOverSplit", value: "0.5", notes: "CreateUnderOver fixed probability at creation" },
    ],
    outputs: [
      {
        name: "highestScoreLine",
        label: "Highest individual score line",
        type: "line",
        csharpPath: "LineSpecifier(Round(MatchHighScore) + adjust + 0.5)",
        excelRef: "PM Publication!F75",
      },
      {
        name: "underOver",
        label: "Under / Over",
        type: "outcome_set",
        csharpPath: "Market.CreateUnderOver(..., 0.5, ...)",
        excelRef: "PM Publication!G75 / H75",
        notes: "Actual probs may differ after engine pricing",
      },
    ],
    missingForParity: [
      "Map MatchHighScore Excel source in Prep Work",
      "Confirm PM Publication F75 line vs Round(highScore)+adjust+0.5",
      "Under/over probabilities after line set (G75/H75)",
    ],
  },
  {
    id: "match-fours",
    registryModelId: "pm-match-fours",
    className: "MatchFours",
    namespace: NS_MATCHES,
    filePath: `${FILE_MATCHES}/MatchFours.cs`,
    phase: "pre_match",
    marketName: "Match Fours",
    marketCode: "51BARUA",
    marketId: 639,
    legacyMarketId: 5,
    description:
      "Match total fours under/over. Limited overs: sum of team fours; Test/FC: MatchFours. Poisson-gamma line from median closest to 0.5.",
    inputs: [
      {
        name: "TeamFours",
        label: "Per-team fours expectation",
        scope: "parameter",
        csharpPath: "team1.GetTeamFours() + team2.GetTeamFours()",
        excelRef: "Prep Work!O36 + O57 (SUM O24:O34 + SUM O45:O55)",
        notes: "Each player fours in column O; team total rows O36 / O57",
      },
      {
        name: "MatchFours",
        label: "Match fours expectation",
        scope: "parameter",
        csharpPath: "inputs.Evaluation.MatchEvaluation.MatchFours",
        notes: "Test/FC path only",
      },
      {
        name: "MatchFoursAdjust",
        label: "Match fours adjust",
        scope: "trading_input",
        csharpPath: "inputs.AdjustmentsPM.MatchAdjustments.MatchFours",
        excelRef: "PM Publication!I52",
        notes: "Purple adjust — added to total before Poisson-gamma line",
      },
      {
        name: "VarianceLookup",
        label: "MatchFours variance",
        scope: "embedded",
        csharpPath: "GetVarianceParameters('MatchFours')",
      },
      {
        name: "OversAvailable",
        label: "Overs available",
        scope: "parameter",
        csharpPath: "inputs.MatchState.GetCurrentInnings().OversAvailable",
      },
    ],
    embeddedConstants: [
      { name: "LineSelection", value: "median(-1) vs median(+1) closest to 0.5" },
      { name: "UnderProbRounding", value: "3dp", notes: "Spreadsheet display" },
      { name: "EmptyMarketGuard", value: "total > 0", notes: "Returns no market if total <= 0" },
    ],
    outputs: [
      {
        name: "foursLine",
        label: "Match fours line",
        type: "line",
        csharpPath: "LineSpecifier(foursLine + 0.5)",
        excelRef: "PM Publication!F52",
      },
      {
        name: "underOver",
        label: "Under / Over",
        type: "outcome_set",
        csharpPath: "GetOverUnderOutcomes(underProb)",
        excelRef: "PM Publication!G52 / H52",
      },
    ],
    missingForParity: [
      "Confirm Poisson-gamma median line vs Excel F52",
      "Under/over probabilities G52/H52 vs GetOverUnderOutcomes(underProb)",
      "MatchEvaluation.MatchFours source for Test/FC (vs team sum path)",
    ],
  },
  {
    id: "match-sixes",
    registryModelId: "pm-match-sixes",
    className: "MatchSixes",
    namespace: NS_MATCHES,
    filePath: `${FILE_MATCHES}/MatchSixes.cs`,
    phase: "pre_match",
    marketName: "Match Sixes",
    marketCode: "52BARUA",
    marketId: 640,
    legacyMarketId: 6,
    description:
      "Match total sixes under/over. Mirror of MatchFours — limited overs sums GetTeamSixes(); Test/FC uses MatchSixes.",
    inputs: [
      {
        name: "TeamSixes",
        label: "Per-team sixes expectation",
        scope: "parameter",
        csharpPath: "team1.GetTeamSixes() + team2.GetTeamSixes()",
        excelRef: "Prep Work!P36 + P57 (SUM P24:P34 + SUM P45:P55)",
        notes: "Each player sixes in column P; team total rows P36 / P57",
      },
      {
        name: "MatchSixes",
        label: "Match sixes expectation",
        scope: "parameter",
        csharpPath: "inputs.Evaluation.MatchEvaluation.MatchSixes",
        notes: "Test/FC path only",
      },
      {
        name: "MatchSixesAdjust",
        label: "Match sixes adjust",
        scope: "trading_input",
        csharpPath: "inputs.AdjustmentsPM.MatchAdjustments.MatchSixes",
        excelRef: "PM Publication!I53",
        notes: "Purple adjust — added to total before Poisson-gamma line",
      },
      {
        name: "VarianceLookup",
        label: "MatchSixes variance",
        scope: "embedded",
        csharpPath: "GetVarianceParameters('MatchSixes')",
      },
      {
        name: "OversAvailable",
        label: "Overs available",
        scope: "parameter",
        csharpPath: "inputs.MatchState.GetCurrentInnings().OversAvailable",
        notes: "MaxOverSpecifier uses maxOvers.ToString()",
      },
    ],
    embeddedConstants: [
      { name: "LineSelection", value: "median(-1) vs median(+1) closest to 0.5" },
      { name: "UnderProbRounding", value: "3dp" },
      { name: "EmptyMarketGuard", value: "total > 0" },
    ],
    outputs: [
      {
        name: "sixesLine",
        label: "Match sixes line",
        type: "line",
        csharpPath: "LineSpecifier(sixesLine + 0.5)",
        excelRef: "PM Publication!F53",
      },
      {
        name: "underOver",
        label: "Under / Over",
        type: "outcome_set",
        csharpPath: "GetOverUnderOutcomes(underProb)",
        excelRef: "PM Publication!G53 / H53",
      },
    ],
    missingForParity: [
      "Confirm Poisson-gamma median line vs Excel F53",
      "Under/over probabilities G53/H53",
      "MatchEvaluation.MatchSixes source for Test/FC",
    ],
  },
  {
    id: "match-run-outs",
    registryModelId: "pm-match-run-outs",
    className: "MatchRunOuts",
    namespace: NS_MATCHES,
    filePath: `${FILE_MATCHES}/MatchRunOuts.cs`,
    phase: "pre_match",
    marketName: "Match Run Outs",
    marketCode: "53BARUA",
    marketId: 654,
    legacyMarketId: 21,
    description:
      "Match run outs under/over. Limited overs: sum InningsRunOuts; Test/FC: MatchRunOuts. Adjust ÷10. Poisson line Round(total−0.8)+0.5.",
    inputs: [
      {
        name: "InningsRunOuts",
        label: "Per-team run outs expectation",
        scope: "parameter",
        csharpPath: "team1.InningsRunOuts + team2.InningsRunOuts",
        excelRef: "Prep Work!U36 + U57",
        notes: "Limited-overs path — team run outs totals below squad",
      },
      {
        name: "MatchRunOuts",
        label: "Match run outs expectation",
        scope: "parameter",
        csharpPath: "inputs.Evaluation.MatchEvaluation.MatchRunOuts",
        notes: "Test/FC path only",
      },
      {
        name: "MatchRunOutsAdjust",
        label: "Match run outs adjust",
        scope: "trading_input",
        csharpPath: "inputs.AdjustmentsPM.MatchAdjustments.MatchRunOuts / 10.0",
        excelRef: "PM Publication!I54",
        notes: "Purple adjust — divided by 10 before adding to total",
      },
      {
        name: "OversAvailable",
        label: "Overs available",
        scope: "parameter",
        csharpPath: "inputs.MatchState.GetCurrentInnings().OversAvailable",
      },
    ],
    embeddedConstants: [
      { name: "LineFormula", value: "Round(total − 0.8) + 0.5" },
      { name: "Distribution", value: "PoissonDistribution(total)" },
      { name: "EmptyMarketGuard", value: "total > 0" },
    ],
    outputs: [
      {
        name: "runOutsLine",
        label: "Match run outs line",
        type: "line",
        csharpPath: "LineSpecifier(runOutLine + 0.5)",
        excelRef: "PM Publication!F54",
      },
      {
        name: "underOver",
        label: "Under / Over",
        type: "outcome_set",
        csharpPath: "GetOverUnderOutcomes(underProb)",
        excelRef: "PM Publication!G54 / H54",
      },
    ],
    missingForParity: [
      "Confirm adjust ÷10 vs Excel I54 raw value",
      "Poisson line Round(total−0.8)+0.5 vs Excel F54",
      "InningsRunOuts source in Prep Work",
    ],
  },
  {
    id: "match-max-over",
    registryModelId: "pm-match-max-over",
    className: "MatchMaxOver",
    namespace: NS_MATCHES,
    filePath: `${FILE_MATCHES}/MatchMaxOver.cs`,
    phase: "pre_match",
    marketName: "Max Runs Scored in an Over",
    marketCode: "54BARUA",
    marketId: 682,
    legacyMarketId: 44,
    description:
      "Under/over on maximum runs scored in any single over. Uses MatchMaxOver from evaluation plus trader adjust. Poisson line Round(total−0.8)+0.5.",
    inputs: [
      {
        name: "MatchMaxOver",
        label: "Max runs in an over expectation",
        scope: "parameter",
        csharpPath: "inputs.Evaluation.MatchEvaluation.MatchMaxOver",
        excelRef: "Prep Work!Z3",
        notes: "T3 Match Max Over model column (20.28 on NZ v SA)",
      },
      {
        name: "MaxRunsInOverAdjust",
        label: "Max runs in over adjust",
        scope: "trading_input",
        csharpPath: "inputs.AdjustmentsPM.MatchAdjustments.MaxRunsInOver",
        excelRef: "PM Publication!I55",
      },
      {
        name: "OversAvailable",
        label: "Overs available",
        scope: "parameter",
        csharpPath: "inputs.MatchState.GetCurrentInnings().OversAvailable",
      },
    ],
    embeddedConstants: [
      { name: "LineFormula", value: "Round(total − 0.8) + 0.5" },
      { name: "Distribution", value: "PoissonDistribution(total)" },
      { name: "EmptyMarketGuard", value: "total > 0" },
    ],
    outputs: [
      {
        name: "maxOverLine",
        label: "Max over runs line",
        type: "line",
        csharpPath: "LineSpecifier(maxOverLine + 0.5)",
        excelRef: "PM Publication!F55",
      },
      {
        name: "underOver",
        label: "Under / Over",
        type: "outcome_set",
        csharpPath: "GetOverUnderOutcomes(underProb)",
        excelRef: "PM Publication!G55 / H55",
      },
    ],
    missingForParity: [
      "MatchMaxOver Excel source in Prep Work",
      "Poisson line vs Excel F55",
    ],
  },
  {
    id: "match-ducks",
    registryModelId: "pm-match-ducks",
    className: "MatchDucks",
    namespace: NS_MATCHES,
    filePath: `${FILE_MATCHES}/MatchDucks.cs`,
    phase: "pre_match",
    marketName: "Match Ducks",
    marketCode: "55BARUA",
    marketId: 695,
    legacyMarketId: 55,
    description:
      "Match ducks under/over. Limited overs: sum InningsDucks; Test/FC: MatchDucks. Adjust ÷10. Poisson-gamma with MatchDucks variance lookup.",
    inputs: [
      {
        name: "InningsDucks",
        label: "Per-team ducks expectation",
        scope: "parameter",
        csharpPath: "team1.InningsDucks + team2.InningsDucks",
        excelRef: "Prep Work!K16:P16 — O16 per innings × 2 teams (1.31 on NZ v SA)",
        notes: "Limited-overs: each team InningsDucks ≈ O16 All blend",
      },
      {
        name: "MatchDucks",
        label: "Match ducks expectation",
        scope: "parameter",
        csharpPath: "inputs.Evaluation.MatchEvaluation.MatchDucks",
        notes: "Test/FC path only",
      },
      {
        name: "MatchDucksAdjust",
        label: "Match ducks adjust",
        scope: "trading_input",
        csharpPath: "inputs.AdjustmentsPM.MatchAdjustments.MatchDucks / 10",
        excelRef: "PM Publication!I56",
        notes: "Purple adjust — divided by 10 before adding to total",
      },
      {
        name: "VarianceLookup",
        label: "MatchDucks variance",
        scope: "embedded",
        csharpPath: "GetVarianceParameters('MatchDucks')",
        notes: "Test/FC forces Constants.Format.Test for lookup key",
      },
      {
        name: "OversAvailable",
        label: "Overs available",
        scope: "parameter",
        csharpPath: "inputs.MatchState.GetCurrentInnings().OversAvailable",
      },
    ],
    embeddedConstants: [
      { name: "LineFormula", value: "Round(total − 0.8) + 0.5" },
      { name: "EmptyMarketGuard", value: "total > 0" },
    ],
    outputs: [
      {
        name: "ducksLine",
        label: "Match ducks line",
        type: "line",
        csharpPath: "LineSpecifier(ducksLine + 0.5)",
        excelRef: "PM Publication!F56",
      },
      {
        name: "underOver",
        label: "Under / Over",
        type: "outcome_set",
        csharpPath: "GetOverUnderOutcomes(underProb)",
        excelRef: "PM Publication!G56 / H56",
      },
    ],
    missingForParity: [
      "Confirm adjust ÷10 vs Excel I56",
      "Poisson-gamma line vs Excel F56 — total 2×O16=1.31 → line 1.5 aligned on NZ v SA",
    ],
  },
  {
    id: "match-wides",
    registryModelId: "pm-match-wides",
    className: "MatchWides",
    namespace: NS_MATCHES,
    filePath: `${FILE_MATCHES}/MatchWides.cs`,
    phase: "pre_match",
    marketName: "Match Wides",
    marketCode: "56BARUA",
    marketId: 696,
    legacyMarketId: 56,
    description:
      "Match wides under/over. Limited overs: sum InningsWides; Test/FC: MatchWides. Poisson-gamma with MatchWides variance lookup.",
    inputs: [
      {
        name: "InningsWides",
        label: "Per-team wides expectation",
        scope: "parameter",
        csharpPath: "team1.InningsWides + team2.InningsWides",
        excelRef: "Prep Work!W38 + W59",
        notes: "Limited-overs path — team wides totals (11.68 on NZ v SA)",
      },
      {
        name: "MatchWides",
        label: "Match wides expectation",
        scope: "parameter",
        csharpPath: "inputs.Evaluation.MatchEvaluation.MatchWides",
        notes: "Test/FC path only",
      },
      {
        name: "MatchWidesAdjust",
        label: "Match wides adjust",
        scope: "trading_input",
        csharpPath: "inputs.AdjustmentsPM.MatchAdjustments.MatchWides",
        excelRef: "PM Publication!I57",
      },
      {
        name: "VarianceLookup",
        label: "MatchWides variance",
        scope: "embedded",
        csharpPath: "GetVarianceParameters('MatchWides')",
      },
      {
        name: "OversAvailable",
        label: "Overs available",
        scope: "parameter",
        csharpPath: "inputs.MatchState.GetCurrentInnings().OversAvailable",
      },
    ],
    embeddedConstants: [
      { name: "LineFormula", value: "Round(total − 0.8) + 0.5" },
      { name: "EmptyMarketGuard", value: "total > 0" },
    ],
    outputs: [
      {
        name: "widesLine",
        label: "Match wides line",
        type: "line",
        csharpPath: "LineSpecifier(widesLine + 0.5)",
        excelRef: "PM Publication!F57",
      },
      {
        name: "underOver",
        label: "Under / Over",
        type: "outcome_set",
        csharpPath: "GetOverUnderOutcomes(underProb)",
        excelRef: "PM Publication!G57 / H57",
      },
    ],
    missingForParity: [
      "InningsWides source in Prep Work",
      "Poisson-gamma line vs Excel F57",
    ],
  },
  {
    id: "match-extras",
    registryModelId: "pm-match-extras",
    className: "MatchExtras",
    namespace: NS_MATCHES,
    filePath: `${FILE_MATCHES}/MatchExtras.cs`,
    phase: "pre_match",
    marketName: "Match Extras",
    marketCode: "57BARUA",
    marketId: 655,
    legacyMarketId: 22,
    description:
      "Match extras under/over. Limited overs: sum ExtrasPrediction; Test/FC: MatchExtras. Total rounded to 2dp. Poisson-gamma with MatchExtras variance (ODI fallback).",
    inputs: [
      {
        name: "ExtrasPrediction",
        label: "Per-team extras expectation",
        scope: "parameter",
        csharpPath: "team1.ExtrasPrediction + team2.ExtrasPrediction",
        excelRef: "Prep Work!M35 + M56",
        notes: "Limited-overs path — team extras rows (18.51 on NZ v SA)",
      },
      {
        name: "MatchExtras",
        label: "Match extras expectation",
        scope: "parameter",
        csharpPath: "inputs.Evaluation.MatchEvaluation.MatchExtras",
        notes: "Test/FC path only",
      },
      {
        name: "MatchExtrasAdjust",
        label: "Match extras adjust",
        scope: "trading_input",
        csharpPath: "inputs.AdjustmentsPM.MatchAdjustments.MatchExtras",
        excelRef: "PM Publication!I58",
      },
      {
        name: "VarianceLookup",
        label: "MatchExtras variance",
        scope: "embedded",
        csharpPath: "GetVarianceParameters('MatchExtras')",
        notes: "GetFormat(inputs, Constants.Format.ODI) fallback",
      },
      {
        name: "OversAvailable",
        label: "Overs available",
        scope: "parameter",
        csharpPath: "inputs.MatchState.GetCurrentInnings().OversAvailable",
      },
    ],
    embeddedConstants: [
      { name: "TotalRounding", value: "Math.Round(total, 2)" },
      { name: "LineFormula", value: "Round(total − 0.8) + 0.5" },
      { name: "EmptyMarketGuard", value: "total > 0" },
    ],
    outputs: [
      {
        name: "extrasLine",
        label: "Match extras line",
        type: "line",
        csharpPath: "LineSpecifier(extrasLine + 0.5)",
        excelRef: "PM Publication!F58",
      },
      {
        name: "underOver",
        label: "Under / Over",
        type: "outcome_set",
        csharpPath: "GetOverUnderOutcomes(underProb)",
        excelRef: "PM Publication!G58 / H58",
      },
    ],
    missingForParity: [
      "ExtrasPrediction source in Prep Work",
      "2dp total rounding vs Excel",
      "Poisson-gamma line vs Excel F58",
    ],
  },
  {
    id: "match-wickets",
    registryModelId: "pm-match-wickets",
    className: "MatchWickets",
    namespace: NS_MATCHES,
    filePath: `${FILE_MATCHES}/MatchWickets.cs`,
    phase: "pre_match",
    marketName: "Match Wickets",
    marketCode: "58BARUA",
    marketId: 639,
    legacyMarketId: 57,
    description:
      "Match wickets under/over. Limited overs: sum WicketsLost; Test/FC: MatchWickets. Custom GetWicketVar (not lookup table). Poisson-gamma line Round(total−0.8)+0.5.",
    inputs: [
      {
        name: "WicketsLost",
        label: "Per-team wickets lost expectation",
        scope: "parameter",
        csharpPath:
          "inputs.Evaluation.GetTeam1Evaluation().WicketsLost + inputs.Evaluation.GetTeam2Evaluation().WicketsLost",
        excelRef: "Prep Work!U38 + U59",
        notes: "Limited-overs path — wickets totals (13.44 on NZ v SA)",
      },
      {
        name: "MatchWickets",
        label: "Match wickets expectation",
        scope: "parameter",
        csharpPath: "inputs.Evaluation.MatchEvaluation.MatchWickets",
        notes: "Test/FC path only",
      },
      {
        name: "MatchWicketsAdjust",
        label: "Match wickets adjust",
        scope: "trading_input",
        csharpPath: "inputs.AdjustmentsPM.MatchAdjustments.MatchWickets",
        excelRef: "PM Publication!I59",
      },
      {
        name: "OversAvailable",
        label: "Overs available",
        scope: "parameter",
        csharpPath: "inputs.MatchState.GetCurrentInnings().OversAvailable",
      },
    ],
    embeddedConstants: [
      { name: "WicketVarFormula", value: "mean² / (−1.54612329915015 × wicketsRemaining) + mean" },
      { name: "WicketsRemaining", value: "40 (Test/FC) or 20 (limited)" },
      { name: "LineFormula", value: "Round(total − 0.8) + 0.5" },
      { name: "EmptyMarketGuard", value: "total > 0" },
      {
        name: "MarketIdCollision",
        value: "639",
        notes: "Same marketId as MatchFours in Lambda — verify PM/Lambda registry",
      },
    ],
    outputs: [
      {
        name: "wicketsLine",
        label: "Match wickets line",
        type: "line",
        csharpPath: "LineSpecifier(wicketsLine + 0.5)",
        excelRef: "PM Publication!F59",
      },
      {
        name: "underOver",
        label: "Under / Over",
        type: "outcome_set",
        csharpPath: "GetOverUnderOutcomes(underProb)",
        excelRef: "PM Publication!G59 / H59",
      },
    ],
    missingForParity: [
      "WicketsLost source in Prep Work",
      "Custom GetWicketVar vs Excel variance",
      "Poisson-gamma line vs Excel F59",
      "marketId 639 shared with MatchFours — confirm correct ID",
    ],
  },
  {
    id: "toss-winner",
    registryModelId: "pm-toss-winner",
    className: "TossWinner",
    namespace: NS_MATCHES,
    filePath: `${FILE_MATCHES}/TossWinner.cs`,
    phase: "pre_match",
    marketName: "Toss Winner",
    marketCode: "54PINB",
    marketId: 694,
    legacyMarketId: 54,
    description: "50/50 toss winner market. No trader adjust in Lambda — fixed equal probabilities.",
    inputs: [
      {
        name: "TeamNames",
        label: "Home / away team names",
        scope: "parameter",
        csharpPath: "GetTeams(inputs) → team1.TeamName, team2.TeamName",
        excelRef: "PM Publication!E24:E25",
      },
      {
        name: "FormatOvers",
        label: "Initial overs for format",
        scope: "parameter",
        csharpPath: "GetInitialOversForFormat(Format)",
      },
    ],
    embeddedConstants: [
      { name: "HomeProb", value: "0.5" },
      { name: "AwayProb", value: "0.5" },
    ],
    outputs: [
      {
        name: "tossOutcomes",
        label: "Toss winner probabilities",
        type: "outcome_set",
        csharpPath: "GetTeamTwoWayOutcomes(..., 0.5, ..., 0.5)",
        excelRef: "PM Publication!G24:G25",
      },
    ],
    missingForParity: ["Confirm Excel also 50/50 vs any venue bias", "Legacy marketId 54 shared with other markets"],
  },
  {
    id: "rabbit-runs",
    registryModelId: "pm-rabbit-runs",
    className: "RabbitRuns",
    namespace: NS_MATCHES,
    filePath: `${FILE_MATCHES}/RabbitRuns.cs`,
    phase: "pre_match",
    marketName: "Rabbit Runs",
    marketCode: "64BARUA",
    marketId: 703,
    legacyMarketId: 63,
    description:
      "Under/over on rabbit (tailender) runs. Uses MatchEvaluation.RabbitRuns only. Adjust subtracts from underProb (÷100), not added to mean.",
    inputs: [
      {
        name: "RabbitRuns",
        label: "Rabbit runs expectation",
        scope: "parameter",
        csharpPath: "inputs.Evaluation.MatchEvaluation.RabbitRuns",
        excelRef: "Prep Work!Y10 (0.965 on NZ v SA)",
        notes: "T10 row — column Y All blend",
      },
      {
        name: "RabbitRunsAdjust",
        label: "Rabbit runs adjust",
        scope: "trading_input",
        csharpPath: "inputs.AdjustmentsPM.MatchAdjustments.RabbitRuns",
        excelRef: "PM Publication!I76",
        notes: "Subtracted from underProb as adjust÷100 — unusual vs other markets",
      },
      {
        name: "VarianceLookup",
        label: "RabbitRuns variance",
        scope: "embedded",
        csharpPath: "GetVarianceParameters('RabbitRuns')",
      },
    ],
    embeddedConstants: [
      { name: "LineFormula", value: "Round(total − 0.8) + 0.5" },
      { name: "AdjustApplication", value: "underProb -= adjust / 100" },
      { name: "EmptyMarketGuard", value: "rabbitRuns > 0" },
    ],
    outputs: [
      {
        name: "rabbitLine",
        label: "Rabbit runs line",
        type: "line",
        csharpPath: "LineSpecifier(line + 0.5)",
        excelRef: "PM Publication!F76",
      },
      {
        name: "underOver",
        label: "Under / Over",
        type: "outcome_set",
        csharpPath: "GetOverUnderOutcomes(underProb)",
        excelRef: "PM Publication!G76 / H76",
        notes: "NZ v SA fixture shows #DIV/0! in G76/H76",
      },
    ],
    missingForParity: [
      "RabbitRuns Excel model source beyond Y10 blend",
      "Adjust subtracts from prob not mean — confirm vs Excel",
      "PM Publication G76/H76 #DIV/0! on fixture",
    ],
  },
  {
    id: "fifty-first-innings",
    registryModelId: "pm-fifty-first-innings",
    className: "FiftyInnings",
    namespace: NS_MATCHES,
    filePath: `${FILE_MATCHES}/MilestoneMarkets.cs`,
    phase: "pre_match",
    marketName: "Fifty in First Innings",
    marketCode: "61BARUA",
    marketId: 700,
    legacyMarketId: 60,
    description: "Yes/No fifty in first innings. MilestoneMarketModel with InningsSpecifier(1) and MilestoneSpecifier(50).",
    inputs: [
      {
        name: "FiftyInnings",
        label: "Fifty in first innings probability",
        scope: "parameter",
        csharpPath: "inputs.Evaluation.MatchEvaluation.FiftyInnings",
        excelRef: "Prep Work!Z5 (0.6505 on NZ v SA)",
      },
      {
        name: "FirstInningsFiftyAdjust",
        label: "First innings fifty adjust",
        scope: "trading_input",
        csharpPath: "inputs.AdjustmentsPM.MatchAdjustments.FirstInningsFifty",
        excelRef: "PM Publication!I67",
        notes: "Added to probability as adjust÷100",
      },
    ],
    embeddedConstants: [
      { name: "Milestone", value: "50" },
      { name: "InningsSpecifier", value: "1" },
      { name: "ProbAdjust", value: "probability += adjust / 100" },
    ],
    outputs: [
      {
        name: "yesNo",
        label: "Yes / No",
        type: "outcome_set",
        csharpPath: "Market.CreateYesNo(..., probability, ...)",
        excelRef: "PM Publication!G67 / G68",
      },
    ],
    missingForParity: [
      "marketId 700 shared with HundredInnings",
      "Fifty in Match (row 69) has no Lambda class in paste",
    ],
  },
  {
    id: "hundred-first-innings",
    registryModelId: "pm-hundred-first-innings",
    className: "HundredInnings",
    namespace: NS_MATCHES,
    filePath: `${FILE_MATCHES}/MilestoneMarkets.cs`,
    phase: "pre_match",
    marketName: "Hundred in First Innings",
    marketCode: "HUNDIN",
    marketId: 700,
    legacyMarketId: 60,
    description: "Yes/No hundred in first innings. Same marketId as FiftyInnings in Lambda.",
    inputs: [
      {
        name: "HundredInnings",
        label: "Hundred in first innings probability",
        scope: "parameter",
        csharpPath: "inputs.Evaluation.MatchEvaluation.HundredInnings",
        excelRef: "Prep Work!Z7 (0.0582 on NZ v SA)",
      },
      {
        name: "FirstInningsHundredAdjust",
        label: "First innings hundred adjust",
        scope: "trading_input",
        csharpPath: "inputs.AdjustmentsPM.MatchAdjustments.FirstInningsHundred",
        excelRef: "PM Publication!I71",
      },
    ],
    embeddedConstants: [
      { name: "Milestone", value: "100" },
      { name: "InningsSpecifier", value: "1" },
    ],
    outputs: [
      {
        name: "yesNo",
        label: "Yes / No",
        type: "outcome_set",
        csharpPath: "Market.CreateYesNo(...)",
        excelRef: "PM Publication!G71 / G72",
      },
    ],
    missingForParity: ["marketId 700 collision with FiftyInnings", "Confirm HUNDIN code in PM"],
  },
  {
    id: "hundred-match",
    registryModelId: "pm-hundred-match",
    className: "HundredMatch",
    namespace: NS_MATCHES,
    filePath: `${FILE_MATCHES}/MilestoneMarkets.cs`,
    phase: "pre_match",
    marketName: "Hundred in Match",
    marketCode: "62BARUA",
    marketId: 701,
    legacyMarketId: 61,
    description: "Yes/No hundred in match. No innings specifier.",
    inputs: [
      {
        name: "HundredMatch",
        label: "Hundred in match probability",
        scope: "parameter",
        csharpPath: "inputs.Evaluation.MatchEvaluation.HundredMatch",
        excelRef: "Prep Work!Z8 (0.084 on NZ v SA)",
      },
      {
        name: "MatchHundredAdjust",
        label: "Match hundred adjust",
        scope: "trading_input",
        csharpPath: "inputs.AdjustmentsPM.MatchAdjustments.MatchHundred",
        excelRef: "PM Publication!I73",
      },
    ],
    embeddedConstants: [{ name: "Milestone", value: "100" }],
    outputs: [
      {
        name: "yesNo",
        label: "Yes / No",
        type: "outcome_set",
        csharpPath: "Market.CreateYesNo(...)",
        excelRef: "PM Publication!G73 / G74",
      },
    ],
    missingForParity: ["Confirm Z8 vs PM G73 after adjust"],
  },
  {
    id: "team-fours",
    registryModelId: "pm-team-fours",
    className: "TeamFours",
    namespace: NS_TEAMS,
    filePath: `${FILE_TEAMS}/TeamFours.cs`,
    phase: "pre_match",
    marketName: "Fours (per team)",
    marketCode: "54PIN / 64PIN",
    marketId: 658,
    legacyMarketId: 26,
    description:
      "Three under/over lines per team on total fours. Expected = GetTeamFours() + InningsFours adjust. Uses MatchFours variance.",
    inputs: [
      {
        name: "TeamFours",
        label: "Team fours expectation",
        scope: "parameter",
        csharpPath: "team.GetTeamFours()",
        excelRef: "Prep Work!O36 (home) / O57 (away)",
      },
      {
        name: "InningsFoursAdjust",
        label: "Innings fours adjust",
        scope: "trading_input",
        csharpPath: "InningsAdjustmentsPM.InningsFours",
        notes: "GetTeam1Adjustments() / GetTeam2Adjustments()",
      },
      {
        name: "VarianceLookup",
        label: "MatchFours variance",
        scope: "embedded",
        csharpPath: "GetVarianceParameters('MatchFours')",
      },
    ],
    embeddedConstants: [
      { name: "LineSet", value: "middle ± max(round(expected/10), 1)" },
      { name: "MiddleLine", value: "round(expected − 0.8)" },
      { name: "MarketsPerTeam", value: "3" },
      { name: "AwayMarketId", value: "659" },
    ],
    outputs: [
      {
        name: "foursLines",
        label: "Three fours lines per team",
        type: "line",
        excelRef: "PM Publication NZ rows 155–157 / SA 221–223",
        notes: "Fours. / Fours / Fours.. templates",
      },
    ],
    missingForParity: [
      "Map InningsFours purple adjust column per team row",
      "Confirm 3-line spread vs PM Fours./Fours/Fours..",
      "marketId 658/659 shared with TeamSixes",
    ],
  },
  {
    id: "team-sixes",
    registryModelId: "pm-team-sixes",
    className: "TeamSixes",
    namespace: NS_TEAMS,
    filePath: `${FILE_TEAMS}/TeamSixes.cs`,
    phase: "pre_match",
    marketName: "Sixes (per team)",
    marketCode: "56PIN / 66PIN",
    marketId: 658,
    legacyMarketId: 27,
    description:
      "Three under/over lines per team on total sixes. Expected = GetTeamSixes() only (no innings adjust in Lambda).",
    inputs: [
      {
        name: "TeamSixes",
        label: "Team sixes expectation",
        scope: "parameter",
        csharpPath: "team.GetTeamSixes()",
        excelRef: "Prep Work!P36 (home) / P57 (away)",
      },
      {
        name: "VarianceLookup",
        label: "MatchSixes variance",
        scope: "embedded",
        csharpPath: "GetVarianceParameters('MatchSixes')",
      },
    ],
    embeddedConstants: [
      { name: "LineSet", value: "middle ± 1" },
      { name: "MarketsPerTeam", value: "3" },
      { name: "AwayMarketId", value: "659" },
      { name: "NoInningsAdjust", value: "true", notes: "Unlike TeamFours" },
    ],
    outputs: [
      {
        name: "sixesLines",
        label: "Three sixes lines per team",
        type: "line",
        excelRef: "PM Publication NZ rows 158–160 / SA 224–226",
      },
    ],
    missingForParity: [
      "No InningsSixes adjust in Lambda — confirm vs Excel",
      "marketId 658/659 collision with TeamFours",
    ],
  },
  {
    id: "team-wickets",
    registryModelId: "pm-team-wickets",
    className: "TeamWickets",
    namespace: NS_TEAMS,
    filePath: `${FILE_TEAMS}/TeamWickets.cs`,
    phase: "pre_match",
    marketName: "Wickets Lost (per team)",
    marketCode: "5WILO / 6WILO",
    marketId: 649,
    legacyMarketId: 18,
    description:
      "Wickets lost by batting team = bowlingTeam.GetTeamRawWickets() / wicketAdjust + battingTeam.InningsRunOuts. Custom Poisson-gamma variance.",
    inputs: [
      {
        name: "TeamRawWickets",
        label: "Opposition raw wickets",
        scope: "parameter",
        csharpPath: "bowlingTeam.GetTeamRawWickets()",
      },
      {
        name: "BattingRating",
        label: "Batting team rating",
        scope: "parameter",
        csharpPath: "battingTeam.BattingRating",
        excelRef: "Prep Work!D4 / I4",
      },
      {
        name: "InningsRunOuts",
        label: "Batting team run outs",
        scope: "parameter",
        csharpPath: "battingTeam.InningsRunOuts",
        excelRef: "Prep Work!U36 / U57",
      },
      {
        name: "Conditions",
        label: "Conditions",
        scope: "parameter",
        csharpPath: "MatchEvaluation.ConditionAdjustment",
        excelRef: "Prep Work!D3",
      },
    ],
    embeddedConstants: [
      { name: "WicketAdjust", value: "0.5 × (batRating/conditions × genderAdjust + 1)" },
      { name: "WomenGenderAdjust", value: "0.78" },
      { name: "VarianceFormula", value: "mean² / −15.4612329915015 + mean" },
      { name: "AwayMarketId", value: "650" },
    ],
    outputs: [
      {
        name: "wicketsLine",
        label: "Wickets lost line",
        type: "line",
        excelRef: "PM Publication NZ row 166 / SA row 232",
      },
    ],
    missingForParity: ["GetTeamRawWickets() Excel source", "wicketAdjust vs Prep Work U38/U59 totals"],
  },
  {
    id: "team-wides",
    registryModelId: "pm-team-wides",
    className: "TeamWides",
    namespace: NS_TEAMS,
    filePath: `${FILE_TEAMS}/TeamWides.cs`,
    phase: "pre_match",
    marketName: "Innings Wides Faced (per team)",
    marketCode: "5INRUB / 6INRUB",
    marketId: 704,
    legacyMarketId: 64,
    description:
      "Wides faced per innings. Expected = InningsWides + InningsAdjustments.WidesBowled.",
    inputs: [
      {
        name: "InningsWides",
        label: "Team wides expectation",
        scope: "parameter",
        csharpPath: "team.InningsWides",
        excelRef: "Prep Work!W38 (home) / W59 (away)",
      },
      {
        name: "WidesBowledAdjust",
        label: "Wides bowled adjust",
        scope: "trading_input",
        csharpPath: "InningsAdjustments[inns].WidesBowled",
      },
      {
        name: "VarianceLookup",
        label: "MatchWides variance",
        scope: "embedded",
        csharpPath: "GetVarianceParameters('MatchWides')",
      },
    ],
    embeddedConstants: [{ name: "AwayMarketId", value: "705" }],
    outputs: [
      {
        name: "widesLine",
        label: "Wides faced line",
        type: "line",
        excelRef: "PM Publication NZ row 163 / SA row 229",
      },
    ],
    missingForParity: ["Map WidesBowled purple adjust per innings"],
  },
  {
    id: "team-ducks",
    registryModelId: "pm-team-ducks",
    className: "TeamDucks",
    namespace: NS_TEAMS,
    filePath: `${FILE_TEAMS}/TeamDucks.cs`,
    phase: "pre_match",
    marketName: "Innings Ducks (per team)",
    marketCode: "54PIN / 64PIN",
    marketId: 706,
    legacyMarketId: 65,
    description:
      "Innings ducks per team. Skipped if InningsDucks ≤ 0. Adjust ÷10. Shares 4PIN code suffix with TeamFours.",
    inputs: [
      {
        name: "InningsDucks",
        label: "Team ducks expectation",
        scope: "parameter",
        csharpPath: "team.InningsDucks",
        excelRef: "Prep Work!O16 per innings (≈0.657)",
      },
      {
        name: "InningsDucksAdjust",
        label: "Innings ducks adjust",
        scope: "trading_input",
        csharpPath: "InningsAdjustmentsPM.InningsDucks / 10.0",
      },
      {
        name: "VarianceLookup",
        label: "MatchDucks variance",
        scope: "embedded",
        csharpPath: "GetVarianceParameters('MatchDucks')",
      },
    ],
    embeddedConstants: [
      { name: "EmptyGuard", value: "InningsDucks > 0" },
      { name: "AwayMarketId", value: "707" },
    ],
    outputs: [
      {
        name: "ducksLine",
        label: "Innings ducks line",
        type: "line",
        excelRef: "PM Publication NZ row 164 / SA row 230",
      },
    ],
    missingForParity: ["4PIN code collision with TeamFours"],
  },
  {
    id: "team-extras",
    registryModelId: "pm-team-extras",
    className: "TeamExtras",
    namespace: NS_TEAMS,
    filePath: `${FILE_TEAMS}/TeamExtras.cs`,
    phase: "pre_match",
    marketName: "Innings Extras (per team)",
    marketCode: "54PINA / 64PINA",
    marketId: 666,
    legacyMarketId: 32,
    description: "Innings extras per team. Expected = ExtrasPrediction + InningsExtras adjust.",
    inputs: [
      {
        name: "ExtrasPrediction",
        label: "Team extras expectation",
        scope: "parameter",
        csharpPath: "team.ExtrasPrediction",
        excelRef: "Prep Work!M35 (home) / M56 (away)",
      },
      {
        name: "InningsExtrasAdjust",
        label: "Innings extras adjust",
        scope: "trading_input",
        csharpPath: "InningsAdjustmentsPM.InningsExtras",
      },
      {
        name: "VarianceLookup",
        label: "MatchExtras variance",
        scope: "embedded",
        csharpPath: "GetVarianceParameters('MatchExtras')",
      },
    ],
    embeddedConstants: [{ name: "AwayMarketId", value: "667" }],
    outputs: [
      {
        name: "extrasLine",
        label: "Innings extras line",
        type: "line",
        excelRef: "PM Publication NZ row 165 / SA row 231",
      },
    ],
    missingForParity: ["Map InningsExtras purple adjust per team row"],
  },
  {
    id: "team-run-outs",
    registryModelId: "pm-team-run-outs",
    className: "TeamRunOuts",
    namespace: NS_TEAMS,
    filePath: `${FILE_TEAMS}/TeamRunOuts.cs`,
    phase: "pre_match",
    marketName: "Innings Run Outs (per team)",
    marketCode: "5INRU / 6INRU",
    marketId: 668,
    legacyMarketId: 33,
    description:
      "Innings run outs — Poisson on expected; underProb = P(X≤0) only. Line specifier fixed at 0.5. Adjust ÷10.",
    inputs: [
      {
        name: "InningsRunOuts",
        label: "Team run outs expectation",
        scope: "parameter",
        csharpPath: "team.InningsRunOuts",
        excelRef: "Prep Work!U36 (home) / U57 (away)",
      },
      {
        name: "InningsRunOutsAdjust",
        label: "Innings run outs adjust",
        scope: "trading_input",
        csharpPath: "InningsAdjustments[inns].InningsRunOuts / 10.0",
      },
    ],
    embeddedConstants: [
      { name: "Distribution", value: "PoissonDistribution(expected)" },
      { name: "UnderProb", value: "GetCumulativeProbability(0) — not line-based" },
      { name: "LineSpecifier", value: "0.5 fixed" },
      { name: "AwayMarketId", value: "669" },
    ],
    outputs: [
      {
        name: "runOutsLine",
        label: "Run outs line",
        type: "line",
        excelRef: "PM Publication NZ row 161 / SA row 227",
        notes: "Effectively over/under 0.5 via Poisson P(0)",
      },
    ],
    missingForParity: [
      "Confirm Poisson P(X≤0) vs PM under/over at 0.5",
      "Different logic from other team O/U markets",
    ],
  },
  {
    id: "team-max-over",
    registryModelId: "pm-team-max-over",
    className: "TeamMaxOver",
    namespace: NS_TEAMS,
    filePath: `${FILE_TEAMS}/TeamMaxOver.cs`,
    phase: "pre_match",
    marketName: "Max Runs in an Over (per team)",
    marketCode: "5INRUA / 6INRUA",
    marketId: 670,
    legacyMarketId: 34,
    description:
      "Per-team max runs in an over. Poisson on InningsMaxOver + MaxRunsInOver adjust. Skipped if InningsMaxOver ≤ 0.",
    inputs: [
      {
        name: "InningsMaxOver",
        label: "Team max over expectation",
        scope: "parameter",
        csharpPath: "team.InningsMaxOver",
        excelRef: "Prep Work!T4 Y=17 (team max over blend)",
        notes: "Match-level T3 Z=20.28 is separate MatchMaxOver market",
      },
      {
        name: "MaxRunsInOverAdjust",
        label: "Max runs in over adjust",
        scope: "trading_input",
        csharpPath: "InningsAdjustments[inns].MaxRunsInOver",
      },
    ],
    embeddedConstants: [
      { name: "LineFormula", value: "Round(InningsMaxOver + adjust − 0.8) + 0.5" },
      { name: "Distribution", value: "PoissonDistribution(InningsMaxOver + adjust)" },
      { name: "EmptyGuard", value: "InningsMaxOver > 0" },
      { name: "AwayMarketId", value: "671" },
    ],
    outputs: [
      {
        name: "maxOverLine",
        label: "Max over runs line",
        type: "line",
        excelRef: "PM Publication NZ row 162 / SA row 228",
      },
    ],
    missingForParity: [
      "Map InningsMaxOver per team in Prep Work",
      "Innings MaxRunsInOver purple adjust column",
    ],
  },
  {
    id: "team-first-partnership",
    registryModelId: "pm-team-first-partnership",
    className: "TeamFirstPartnership",
    namespace: NS_TEAMS,
    filePath: `${FILE_TEAMS}/TeamFirstPartnership.cs`,
    phase: "pre_match",
    marketName: "Runs at Fall of 1st Wicket",
    marketCode: "11FONW / 21FONW",
    marketId: 349,
    legacyMarketId: 129,
    description:
      "Per-team first-wicket partnership line. Openers expected runs × format multiplier × meanMedianMultiplier + batter adjusts + FallOfWicket. Fixed 50/50 outcomes.",
    inputs: [
      {
        name: "OpenerExpectedRuns",
        label: "Opener 1 & 2 expected runs",
        scope: "parameter",
        csharpPath: "PlayerEvaluations[0/1].BatsmanEvaluation.ExpectedRuns (or BattingAverage if T10)",
        notes: "Per team — not averaged across both teams like match FirstPartnership",
      },
      {
        name: "FallOfWicketAdjust",
        label: "Fall of wicket adjust",
        scope: "trading_input",
        csharpPath: "InningsAdjustmentsPM.FallOfWicket",
        notes: "Added directly to run line (int)",
      },
      {
        name: "BatterAdjustments",
        label: "Opener batsman run adjusts",
        scope: "trading_input",
        csharpPath: "BatterAdjustments[0/1].BatsmanRuns",
        notes: "0.5 × sum added to line before FallOfWicket",
      },
    ],
    embeddedConstants: [
      { name: "FormatMultiplier", value: "Test=1.0, ODI=1.025, else 1.05" },
      { name: "MeanMedianMultiplier", value: "Test=0.66, T20=0.72, T10=0.74, else 0.69" },
      { name: "LineFormula", value: "Round(0.5×(bat1+bat2)×mult×meanMedian + 0.5×batterAdjs) + FallOfWicket" },
      { name: "Outcomes", value: "GetOverUnderOutcomes(0.5) — fixed, not priced from distribution" },
      { name: "AwayMarketId", value: "350" },
      { name: "ExtraSpecifiers", value: "So far=0, LineDelta=0, WicketSpecifier(1)" },
    ],
    outputs: [
      {
        name: "partnershipLine",
        label: "Runs at fall of 1st wicket line",
        type: "line",
        csharpPath: "LineSpecifier(runLine + 0.5)",
        excelRef: "PM Publication NZ row 147 / SA row 213",
      },
      {
        name: "underOver",
        label: "Under / Over",
        type: "outcome_set",
        csharpPath: "GetOverUnderOutcomes(0.5)",
        notes: "Engine prices to 50/50 — compare match FirstPartnership row 44",
      },
    ],
    missingForParity: [
      "Match FirstPartnership uses Log(2) and 4-opener average — team version differs",
      "legacyMarketId 129 shared with match FirstPartnership (999)",
      "Opener ExpectedRuns cells in Prep Work",
    ],
  },
  {
    id: "team-first-dismissal",
    registryModelId: "pm-team-first-dismissal",
    className: "TeamFirstDismissal",
    namespace: NS_TEAMS,
    filePath: `${FILE_TEAMS}/TeamFirstDismissal.cs`,
    phase: "pre_match",
    marketName: "1st Wicket Method of Dismissal (per team)",
    marketCode: "11MOPD / 21MOPD",
    marketId: 816,
    legacyMarketId: 25,
    description:
      "Per-team first dismissal method market. Both openers × opposition bowling dismissal rates, each weighted ÷2. No PM trader adjusts in Lambda (unlike match FirstDismissal).",
    inputs: [
      {
        name: "DismissalMethodRates",
        label: "Opposition bowling dismissal methods",
        scope: "parameter",
        csharpPath: "bowlingTeam.DismissalMethodEvaluation (Fielder, Bowled, Keeper, LBW, RunOut, Stumped, Other)",
        excelRef: "Prep Work!AD3:AM18",
        notes: "Same source as match FirstDismissal",
      },
      {
        name: "OpenerPlayerAdjusts",
        label: "Opener batting adjusts",
        scope: "parameter",
        csharpPath: "GetFielderCatchAdjust, GetBowledAdjust, GetStumpedAdjust — keeper/LBW/run out/other fixed at 1.0",
      },
      {
        name: "BatterRunsLookup",
        label: "Format batter runs lookup",
        scope: "embedded",
        csharpPath: "LookupProvider.GetBatterRunsLookup()",
      },
      {
        name: "StrikeRateLookup",
        label: "Format strike rate lookup",
        scope: "embedded",
        csharpPath: "LookupProvider.GetStrikeRateLookup()",
      },
    ],
    embeddedConstants: [
      { name: "OpenersPerTeam", value: "2 (not 4 like match market)" },
      { name: "WeightPerOpener", value: "÷2 per method" },
      { name: "WomenFormatKey", value: "w{format} for T20/ODI women's" },
      { name: "AwayMarketId", value: "817" },
      { name: "NoTraderAdjusts", value: "true", notes: "Match FirstDismissal applies PM adjusts ÷100" },
    ],
    outputs: [
      {
        name: "dismissalOutcomes",
        label: "7 dismissal method probabilities",
        type: "outcome_set",
        csharpPath: "FielderCatch, Bowled, KeeperCatch, LBW, RunOut, Stumped, Other",
        excelRef: "PM Publication NZ rows 148–154 / SA rows 214–220",
      },
    ],
    missingForParity: [
      "No PM trader adjusts in Lambda — confirm Excel I-column per selection",
      "legacyMarketId 25 shared with match FirstDismissal (718)",
      "Compare per-team probs vs match FirstDismissal rows 45–51",
      "CommonMethods.GetLookupFormat dependency (Overs namespace import)",
    ],
  },
];
