/**
 * Excel cell conventions for cricket pricing workbooks.
 * Purple cells = trader adjusts. Pre-match adjusts: PM Publication column I.
 * Live adjusts: Scoring and UI tabs (purple cells).
 *
 * @see trader-adjust-conventions.ts — adjusts are applied on the FE after Lambda runs (±0.01 prob via I÷100 on most markets).
 */

export const excelConventions = {
  preMatchAdjustColumn: "I",
  preMatchAdjustSheet: "PM Publication",
  liveAdjustSheets: ["Scoring", "UI"],
  adjustCellNote:
    "Purple cells — per-row trader skew applied after the model (typically I÷100 → ±0.01 probability). See Prep Work E10 / G67 pattern.",
};

export const prepWorkMappings = {
  conditions: { cell: "D3", feeds: "MatchEvaluation.ConditionAdjustment" },
  teamBattingRatings: {
    cells: ["D4", "I4"],
    labels: ["Team 1 batting", "Team 2 batting"],
    feeds: "TeamEvaluation.BattingRating",
    derivedFrom: "Player batting ratings (e.g. Q24 formula) rolled up to team",
  },
  teamBowlingRatings: {
    cells: ["D5", "I5"],
    feeds: "TeamEvaluation.BowlingRating",
    derivedFrom: "Player bowling ratings (e.g. Z24 formula) rolled up to team",
  },
  totalFactor: {
    cells: ["D6", "I6"],
    labels: ["Team 1 total factor", "Team 2 total factor"],
    formula: "battingRating × oppositionBowlingRating × conditions (D3)",
    feeds: "Intermediate for expected innings runs",
  },
  expectedInningsRuns: {
    cells: ["E6", "J6"],
    labels: ["Team 1 expected runs", "Team 2 expected runs"],
    formula: "totalFactor × parScore (BT3)",
    feeds: "TeamEvaluation.GetRunsExpected() — used by TopBatterMethods.GetCap",
    lambdaEquivalent: "MatchBetting.GetInningsRuns: batRating × bowlRating × conditions × formatStandard",
  },
  parScore: {
    cell: "BT3",
    feeds: "Format baseline runs in Excel",
    notes:
      "NZ v SA fixture is T20 (BT3=165 ≈ Lambda T20Standard=163). Prep Work A1 may still show 'Test' — treat par score as authoritative.",
  },
  traderAdjustExample: {
    cell: "E10",
    usedIn: "Prep Work!C10 = Pricing!J30 + E10/100",
    notes: "÷100 skew unit — same idea as PM Publication I on many probability rows",
  },
  perInningsHistorical: {
    range: "K2:P18",
    weightColumns: { L: "Venue", M: "Host", N: "Cmptn", O: "All", P: "Last 5 Yrs" },
    wickets: { row: 4, allCell: "O4", feeds: "Par / historical innings wickets" },
    extras: { row: 14, allCell: "O14", feeds: "Per-innings extras blend (8.23 on NZ v SA)" },
    wides: { row: 15, allCell: "O15", feeds: "Par wides — W39/W60 pars reference O15" },
    ducks: {
      row: 16,
      range: "K16:P16",
      allCell: "O16",
      cells: { K: "Ducks", L: 0.737, M: 0.661, N: 0.732, O: 0.657, P: 0.720 },
      feeds: "InningsDucks per team ≈ O16; match sum = 2×O16 → MatchDucks",
    },
    runOuts: { row: 17, allCell: "O17", feeds: "Per-innings run outs blend (0.42)" },
  },
  matchLevelModelBlock: {
    range: "T2:Z17",
    weightColumns: { U: "Venue", V: "Host", W: "Cmptn", X: "3 Yr Cm", Y: "All", Z: "Model" },
    matchMaxOver: { row: 3, modelCell: "Z3", allCell: "Y3", feeds: "MatchEvaluation.MatchMaxOver" },
    fiftyFirstInnings: { row: 5, modelCell: "Z5", feeds: "MatchEvaluation.FiftyInnings" },
    hundredFirstInnings: { row: 7, modelCell: "Z7", feeds: "MatchEvaluation.HundredInnings" },
    hundredMatch: { row: 8, modelCell: "Z8", feeds: "MatchEvaluation.HundredMatch" },
    rabbitRuns: { row: 10, allCell: "Y10", feeds: "MatchEvaluation.RabbitRuns" },
    highestScore: { row: 9, modelCell: "Z9", feeds: "MatchEvaluation.MatchHighScore" },
  },
  teamInningsTotals: {
    homeBlock: "B23:F39",
    awayBlock: "B44:F60",
    homeExtras: "M35",
    awayExtras: "M56",
    homeRunOuts: "U36",
    awayRunOuts: "U57",
    homeWickets: "U38",
    awayWickets: "U59",
    homeWides: "W38",
    awayWides: "W59",
    feeds: {
      extras: "ExtrasPrediction per team → MatchExtras limited-overs sum",
      runOuts: "InningsRunOuts per team → MatchRunOuts sum",
      wickets: "WicketsLost per team → MatchWickets sum",
      wides: "InningsWides per team → MatchWides sum",
    },
  },
  playerFoursSixes: {
    foursHeader: "Prep Work!O23",
    sixesHeader: "Prep Work!P23",
    team1PlayerFours: "O24:O34",
    team1PlayerSixes: "P24:P34",
    team1FoursTotal: "O36",
    team1SixesTotal: "P36",
    team2PlayerFours: "O45:O55",
    team2PlayerSixes: "P45:P55",
    team2FoursTotal: "O57",
    team2SixesTotal: "P57",
    feeds: "TeamEvaluation.GetTeamFours() / GetTeamSixes()",
    notes: "Each player row has expected fours (O) and sixes (P); team total is sum of XI",
  },
  matchProbabilities: { cells: ["C10", "C11"], labels: ["Home win %", "Away win %"] },
  matchPrices: { cells: ["D10", "D11"], labels: ["Home price", "Away price"] },
  playerBattingRatingFormula: {
    exampleCell: "Q24",
    rowContext: "Row 24 = first home batter (DP Conway in NZ v SA fixture)",
    notes: "Formula combines prep inputs into per-player batting rating",
  },
  playerBowlingRatingFormula: {
    exampleCell: "Z24",
    notes: "Formula combines prep inputs into per-player bowling rating",
  },
  dismissalMethodRates: {
    range: "AD3:AM18",
    structure: [
      "AD4:AD9 — NZ bowling method rates vs SA batting (Fielder…Stumped)",
      "AD12:AD17 — SA bowling method rates vs NZ batting",
      "Columns AF/AH — Host / Cmptn / All weightings",
    ],
    feeds: "TeamEvaluation.DismissalMethodEvaluation",
  },
  dismissalProbabilities: {
    range: "AO4:AQ10",
    rows: {
      4: "Fielder Catch",
      5: "Bowled",
      6: "Keeper Catch",
      7: "LBW",
      8: "Run Out",
      9: "Stumped",
      10: "Samples (row 10 — not a probability)",
    },
    columns: { AO: "Host", AP: "Cmptn", AQ: "All" },
    notes: "Rows 4–9 are outcome probabilities; compare to PM Publication G45:G51",
  },
};

export const pmPublicationMappings = {
  probabilityColumn: "G",
  adjustColumn: "I",
  priceColumn: "J",
  markets: [
    {
      modelId: "pm-match-winner",
      rows: "20-21",
      market: "Match Betting (2-way)",
      adjustCells: ["I20", "I21"],
      probabilityCells: ["G20", "G21"],
      lambdaAdjust: "AdjustmentsPM.MatchAdjustments.MatchBetting",
      notes: "Lambda uses single home-team adjust; Excel may set I20 (home) only",
    },
    {
      modelId: "pm-first-partnership",
      rows: "44",
      market: "Runs in First Partnership",
      adjustCell: "I44",
      lineCell: "F44",
      lambdaAdjust: "AdjustmentsPM.MatchAdjustments.FirstPartnership",
    },
    {
      modelId: "pm-group-runs",
      rows: "38-40",
      market: "Runs in First N Overs (match)",
      adjustCell: "I38",
      lineCell: "F38",
      lambdaAdjust: "AdjustmentsPM.MatchAdjustments.FirstGroup / SecondGroup / ThirdGroup",
      notes: "T20 rows 38–40 = 6/8/10 overs. Line = Round(mean−1.2)+0.5. Group-specific adjust by over count.",
    },
    {
      modelId: "pm-group-wickets",
      rows: "41-43",
      market: "Wickets in First N Overs",
      adjustCell: "I41",
      lineCell: "F41",
      lambdaAdjust: "MatchAdjustments.FirstGroupWickets / SecondGroupWickets / ThirdGroupWickets (÷10 in Lambda)",
      notes: "T20 rows 41–43. Line = Round(mean−0.8)+0.5",
    },
    {
      modelId: "pm-team-group-runs",
      rows: "NZ 138-146 / SA 204-212",
      market: "{Team} Runs in First N Overs",
      lambdaAdjust: "InningsAdjustmentsPM.FirstGroup / SecondGroup / ThirdGroup",
      notes: "Three lines per team per group (. and .. suffix rows = alternate lines). TeamGroupRuns or GroupRuns team branch.",
    },
    {
      modelId: "pm-first-dismissal",
      rows: "45-51",
      market: "Method of First Dismissal",
      selections: [
        { row: 45, selection: "Fielder Catch", prob: "G45", adjust: "I45", lambda: "FielderCatch" },
        { row: 46, selection: "Bowled", prob: "G46", adjust: "I46", lambda: "Bowled" },
        { row: 47, selection: "Keeper Catch", prob: "G47", adjust: "I47", lambda: "KeeperCatch" },
        { row: 48, selection: "LBW", prob: "G48", adjust: "I48", lambda: "Lbw" },
        { row: 49, selection: "Run Out", prob: "G49", adjust: "I49", lambda: "RunOut" },
        { row: 50, selection: "Stumped", prob: "G50", adjust: "I50", lambda: "Stumped" },
        { row: 51, selection: "Other", prob: "G51", adjust: "I51", lambda: "Other" },
      ],
      notes:
        "7-way partition — probs sum to 1. PM Pricing r53–59: G[row]=AVERAGE(J:M)+I/100; C[row]=G/G$60; G45=PM Pricing C53. Adjust adds to weight then whole market renormalises (paired ±1 transfers 0.01 between outcomes).",
    },
    {
      modelId: "pm-highest-individual-score",
      rows: "75",
      market: "Highest Individual Score",
      adjustCell: "I75",
      lineCell: "F75",
      lambdaAdjust: "AdjustmentsPM.MatchAdjustments.HighestIndividualScore",
      notes: "Line = Round(MatchHighScore) + adjust + 0.5",
    },
    {
      modelId: "pm-match-fours",
      rows: "52",
      market: "Match Fours",
      adjustCell: "I52",
      lineCell: "F52",
      lambdaAdjust: "AdjustmentsPM.MatchAdjustments.MatchFours",
      notes: "Total = SUM(player O col) both teams + I52 purple adjust; line from Poisson-gamma median",
    },
    {
      modelId: "pm-match-sixes",
      rows: "53",
      market: "Match Sixes",
      adjustCell: "I53",
      lineCell: "F53",
      lambdaAdjust: "AdjustmentsPM.MatchAdjustments.MatchSixes",
      notes: "Total = SUM(player P col) both teams + I53 purple adjust; line from Poisson-gamma median",
    },
    {
      modelId: "pm-match-run-outs",
      rows: "54",
      market: "Match Run Outs",
      adjustCell: "I54",
      lineCell: "F54",
      lambdaAdjust: "AdjustmentsPM.MatchAdjustments.MatchRunOuts",
      notes: "Lambda divides adjust by 10; line = Round(total−0.8)+0.5 via Poisson",
    },
    {
      modelId: "pm-match-max-over",
      rows: "55",
      market: "Max Runs Scored in an Over",
      adjustCell: "I55",
      lineCell: "F55",
      lambdaAdjust: "AdjustmentsPM.MatchAdjustments.MaxRunsInOver",
      notes: "MatchMaxOver + adjust; Poisson line Round(total−0.8)+0.5",
    },
    {
      modelId: "pm-match-ducks",
      rows: "56",
      market: "Match Ducks",
      adjustCell: "I56",
      lineCell: "F56",
      lambdaAdjust: "AdjustmentsPM.MatchAdjustments.MatchDucks",
      notes: "Per-innings ducks K16:P16 — O16 per team, sum 2×O16=1.31 → line 1.5; adjust÷10",
    },
    {
      modelId: "pm-match-wides",
      rows: "57",
      market: "Match Wides",
      adjustCell: "I57",
      lineCell: "F57",
      lambdaAdjust: "AdjustmentsPM.MatchAdjustments.MatchWides",
      notes: "InningsWides sum or MatchWides; Poisson-gamma with MatchWides variance lookup",
    },
    {
      modelId: "pm-match-extras",
      rows: "58",
      market: "Match Extras",
      adjustCell: "I58",
      lineCell: "F58",
      lambdaAdjust: "AdjustmentsPM.MatchAdjustments.MatchExtras",
      notes: "ExtrasPrediction sum or MatchExtras; total rounded to 2dp before line",
    },
    {
      modelId: "pm-match-wickets",
      rows: "59",
      market: "Match Wickets",
      adjustCell: "I59",
      lineCell: "F59",
      lambdaAdjust: "AdjustmentsPM.MatchAdjustments.MatchWickets",
      notes: "Limited overs: U38+U59 (13.44) → line 13.5; Test: T17!Y MatchWickets",
    },
    {
      modelId: "pm-first-innings-lead",
      rows: "64-66",
      market: "First Innings Lead",
      adjustCell: "I64",
      probabilityCells: ["G64", "G65", "G66"],
      lambdaAdjust: "AdjustmentsPM.MatchAdjustments.FirstInningsLead",
      notes:
        "3-way race — home/away/tie. Lambda: RaceDistribution on Poisson-gamma innings totals; adjust shifts home vs away (÷100).",
    },
    {
      modelId: "pm-highest-opening-partnership",
      rows: "92-94",
      market: "Highest Opening Partnership",
      adjustCells: ["I92", "I94"],
      probabilityCells: ["G92", "G93", "G94"],
      lambdaAdjust:
        "MatchAdjustments.HighestOpeningPartnership + HighestOpeningPartnershipTie",
      notes:
        "3-way opening-partnership race. homeProb + homeAdj/100 − tieAdj/100; awayProb − homeAdj/100. Test/FC market name prefixed \"1st Innings\".",
    },
    {
      modelId: "pm-most-wickets",
      rows: "544-546",
      market: "To Take Most Wickets",
      adjustCells: ["I544", "I546"],
      probabilityCells: ["G544", "G545", "G546"],
      lambdaAdjust: "MatchAdjustments.MostWickets + MostWicketsTie",
      notes:
        "3-way top-bowler wicket race. PlayerSpecifiers name nominated bowlers; same home/tie adjust pattern as HOP.",
    },
    {
      modelId: "pm-toss-winner",
      rows: "24-25",
      market: "Toss Winner",
      probabilityCells: ["G24", "G25"],
      notes: "Lambda fixed 50/50 — no trader adjust in TossWinner.cs",
    },
    {
      modelId: "pm-fifty-first-innings",
      rows: "67-68",
      market: "Fifty in First Innings",
      adjustCell: "I67",
      probabilityCells: ["G67", "G68"],
      lambdaAdjust: "AdjustmentsPM.MatchAdjustments.FirstInningsFifty",
      notes: "Prep Work Z5=0.6505 ≈ PM G67=0.65",
    },
    {
      modelId: "pm-hundred-first-innings",
      rows: "71-72",
      market: "Hundred in First Innings",
      adjustCell: "I71",
      probabilityCells: ["G71", "G72"],
      lambdaAdjust: "AdjustmentsPM.MatchAdjustments.FirstInningsHundred",
      notes: "Prep Work Z7=0.0582 ≈ PM G71=0.058",
    },
    {
      modelId: "pm-hundred-match",
      rows: "73-74",
      market: "Hundred in Match",
      adjustCell: "I73",
      probabilityCells: ["G73", "G74"],
      lambdaAdjust: "AdjustmentsPM.MatchAdjustments.MatchHundred",
      notes: "Prep Work Z8=0.084 ≈ PM G73=0.084",
    },
    {
      modelId: "pm-rabbit-runs",
      rows: "76",
      market: "Rabbit Runs",
      adjustCell: "I76",
      lineCell: "F76",
      lambdaAdjust: "AdjustmentsPM.MatchAdjustments.RabbitRuns",
      notes: "Prep Work Y10=0.965; Lambda subtracts adjust÷100 from underProb (not added to total)",
    },
    {
      modelId: "pm-player-runs",
      rows: "257-266",
      market: "Player - Runs",
      notes: "One row per selected batter; line F, prob G≈0.5, adjust I per player",
    },
    {
      modelId: "pm-player-fours",
      rows: "267-276",
      market: "Player - Fours",
      notes: "Line Round(ExpectedFours/2); BatsmanFours adjust÷10; Prep Work O per player",
    },
    {
      modelId: "pm-player-sixes",
      rows: "277-286",
      market: "Player - Sixes",
      notes: "Line 0 (F=0.5 placeholder); Poisson-gamma under prob in G",
    },
    {
      modelId: "pm-player-performance",
      rows: "337-346",
      market: "Player - Player Perf",
      notes: "Top 5 per team; line Round(points×0.9); trader adjust in I (no Lambda adjust yet)",
    },
    {
      modelId: "pm-player-balls-faced",
      rows: "610-619",
      market: "Player - Balls Faced",
      notes: "Line from expected runs/strike rate; fixed 50/50 in Lambda",
    },
    {
      modelId: "pm-team-fours",
      rows: "NZ 155-157 / SA 221-223",
      market: "{Team} Fours (3 lines)",
      lambdaAdjust: "InningsAdjustmentsPM.InningsFours",
      notes: "GetTeamFours() + adjust; middle ± max(round(expected/10),1)",
    },
    {
      modelId: "pm-team-sixes",
      rows: "NZ 158-160 / SA 224-226",
      market: "{Team} Sixes (3 lines)",
      notes: "GetTeamSixes(); middle ± 1; no innings adjust in Lambda",
    },
    {
      modelId: "pm-team-run-outs",
      rows: "NZ 161 / SA 227",
      market: "{Team} Innings Run Outs",
      lambdaAdjust: "InningsAdjustments.InningsRunOuts / 10",
      notes: "Poisson P(X≤0); line 0.5",
    },
    {
      modelId: "pm-team-wides",
      rows: "NZ 163 / SA 229",
      market: "{Team} Innings Wides Faced",
      lambdaAdjust: "InningsAdjustments.WidesBowled",
      notes: "InningsWides + adjust; Prep Work W38/W59",
    },
    {
      modelId: "pm-team-ducks",
      rows: "NZ 164 / SA 230",
      market: "{Team} Innings Ducks",
      lambdaAdjust: "InningsAdjustments.InningsDucks / 10",
      notes: "InningsDucks from O16; skipped if ≤0",
    },
    {
      modelId: "pm-team-extras",
      rows: "NZ 165 / SA 231",
      market: "{Team} Innings Extras",
      lambdaAdjust: "InningsAdjustments.InningsExtras",
      notes: "ExtrasPrediction M35/M56 + adjust",
    },
    {
      modelId: "pm-team-wickets",
      rows: "NZ 166 / SA 232",
      market: "{Team} Wickets Lost",
      notes: "GetTeamRawWickets / wicketAdjust + InningsRunOuts",
    },
    {
      modelId: "pm-team-max-over",
      rows: "NZ 162 / SA 228",
      market: "{Team} Max Runs in an Over",
      lambdaAdjust: "InningsAdjustments.MaxRunsInOver",
      notes: "InningsMaxOver + adjust; Poisson line; skipped if ≤0",
    },
    {
      modelId: "pm-team-first-partnership",
      rows: "NZ 147 / SA 213",
      market: "{Team} Runs at Fall of 1st Wicket",
      lambdaAdjust: "InningsAdjustmentsPM.FallOfWicket + BatterAdjustments",
      notes: "Per-team opener line; fixed 50/50 outcomes — differs from match FirstPartnership row 44",
    },
    {
      modelId: "pm-team-first-dismissal",
      rows: "NZ 148-154 / SA 214-220",
      market: "{Team} 1st Wicket Method of Dismissal",
      notes: "7 selections per team; Prep Work AD:AM dismissal rates; no PM adjust in Lambda",
    },
  ],
};

/** NZ v SA fixture — extracted values for parity checks */
export const nzSaDismissalProbabilities = [
  { method: "Fielder Catch", prepWorkAQ: 0.5685923742034427, pmPublicationG: 0.5947912651135385, row: 45 },
  { method: "Bowled", prepWorkAQ: 0.17502855707448636, pmPublicationG: 0.1627772821952726, row: 46 },
  { method: "Keeper Catch", prepWorkAQ: 0.10276831751236151, pmPublicationG: 0.11247662817740745, row: 47 },
  { method: "LBW", prepWorkAQ: 0.06585314260028029, pmPublicationG: 0.05332098054426765, row: 48 },
  { method: "Run Out", prepWorkAQ: 0.0609589095428224, pmPublicationG: 0.05296730697292155, row: 49 },
  { method: "Stumped", prepWorkAQ: 0.02507998625029747, pmPublicationG: 0.021668208953639207, row: 50 },
  { method: "Other", prepWorkAQ: null, pmPublicationG: 0.0019983280429531065, row: 51 },
];

export const nzSaDismissalMethodRates = {
  nzBowlingVsSaBatting: {
    range: "AD4:AH9",
    methods: ["Fielder", "Bowled", "Keeper", "LBW", "Run Out", "Stumped"],
    hostValues: [0.699, 0.097, 0.133, 0.026, 0.029, 0.014],
  },
  saBowlingVsNzBatting: {
    range: "AD12:AH17",
    hostValues: [0.305, 0.395, 0.305, 0, -0.005, 0],
  },
};

export const nzSaPlayerRatingExamples = {
  batter: { player: "DP Conway", row: 24, battingRatingCell: "Q24", value: 1.4902291091098339 },
  bowler: { bowlingRatingCell: "Z24", value: -0.935999999999996, styleCell: "AA24", style: "seam" },
};
