import type { WorkbookSnapshot } from "@/lib/types";
import { nzSaFoursSixes } from "./prep-player-stats";
import { nzSaTeamInningsTotals } from "./prep-match-stats";

/** Extracted from: New Zealand v South Africa 63406779 (1).xlsm — pre-match state (T20) */
export const nzSaWorkbook: WorkbookSnapshot = {
  id: "nz-sa-63406779",
  filename: "New Zealand v South Africa 63406779 (1).xlsm",
  matchId: "63406779",
  homeTeam: "New Zealand",
  awayTeam: "South Africa",
  venue: "Seddon Park",
  format: "T20",
  phase: "pre_match",
};

export const nzSaMatchMarket = {
  marketType: "2W",
  sheet: "Prep Work",
  selections: [
    {
      team: "New Zealand",
      probability: 0.61036254423642,
      price: 1.6383705216561526,
      probabilityCell: "C10",
      priceCell: "D10",
    },
    {
      team: "South Africa",
      probability: 0.38963745576358,
      price: 2.5664883732501558,
      probabilityCell: "C11",
      priceCell: "D11",
    },
  ],
  alsoPublished: [
    { sheet: "PM Publication", probabilityCells: ["G14", "G15"], market: "Match Betting (3-Way)" },
    { sheet: "PM Publication", probabilityCells: ["G20", "G21"], market: "Match Betting (2-way)" },
  ],
};

export const nzSaPrepInputs = [
  {
    id: "conditions",
    label: "Conditions",
    cell: "Prep Work!D3",
    namedRange: null,
    value: 1.01,
    scope: "parameter" as const,
  },
  {
    id: "batting-rating-nz",
    label: "New Zealand Batting",
    cell: "Prep Work!D4",
    namedRange: "battingRating1",
    value: 1.0432168503317343,
    scope: "parameter" as const,
  },
  {
    id: "batting-rating-sa",
    label: "South Africa Batting",
    cell: "Prep Work!I4",
    namedRange: "battingRating2",
    value: 0.979307824664271,
    scope: "parameter" as const,
  },
  {
    id: "bowling-rating-sa",
    label: "South Africa Bowling",
    cell: "Prep Work!D5",
    namedRange: "bowlingRating1",
    value: 1.0090375757575758,
    scope: "parameter" as const,
  },
  {
    id: "bowling-rating-nz",
    label: "New Zealand Bowling",
    cell: "Prep Work!I5",
    namedRange: "bowlingRating2",
    value: 1.001520606060606,
    scope: "parameter" as const,
  },
  {
    id: "total-factor-nz",
    label: "Total Factor (NZ bat)",
    cell: "Prep Work!D6",
    namedRange: null,
    value: 1.0631714516646689,
    scope: "parameter" as const,
    notes: "D4 × D5 × D3 — batting × opposition bowling × conditions",
  },
  {
    id: "expected-runs-nz",
    label: "Expected Innings Runs (NZ)",
    cell: "Prep Work!E6",
    namedRange: null,
    value: 175.42328952467037,
    scope: "parameter" as const,
    notes: "D6 × BT3 — maps to TeamEvaluation.GetRunsExpected() when NZ bats",
  },
  {
    id: "total-factor-sa",
    label: "Total Factor (SA bat)",
    cell: "Prep Work!I6",
    namedRange: null,
    value: 0.9906049357384309,
    scope: "parameter" as const,
    notes: "I4 × I5 × D3",
  },
  {
    id: "expected-runs-sa",
    label: "Expected Innings Runs (SA)",
    cell: "Prep Work!J6",
    namedRange: null,
    value: 163.4498143968411,
    scope: "parameter" as const,
    notes: "I6 × BT3 — maps to TeamEvaluation.GetRunsExpected() when SA bats",
  },
  {
    id: "par-score",
    label: "Par score (format baseline)",
    cell: "Prep Work!BT3",
    namedRange: null,
    value: 165,
    scope: "embedded" as const,
    notes: "T20 par (165) × total factor for E6/J6 — aligns with Lambda T20Standard≈163",
  },
  {
    id: "team1-fours",
    label: "Team 1 fours (sum of players)",
    cell: "Prep Work!O36",
    namedRange: null,
    value: nzSaFoursSixes.team1Fours.value,
    scope: "parameter" as const,
    notes: "SUM(O24:O34) — maps to GetTeamFours() for home team",
  },
  {
    id: "team2-fours",
    label: "Team 2 fours (sum of players)",
    cell: "Prep Work!O57",
    namedRange: null,
    value: nzSaFoursSixes.team2Fours.value,
    scope: "parameter" as const,
    notes: "SUM(O45:O55) — maps to GetTeamFours() for away team",
  },
  {
    id: "match-fours-total",
    label: "Match fours (limited overs)",
    cell: "Prep Work!O36+O57",
    namedRange: null,
    value: nzSaFoursSixes.matchFoursLimited.value,
    scope: "parameter" as const,
    notes: "Team1 + team2 fours before PM Publication I52 adjust",
  },
  {
    id: "team1-sixes",
    label: "Team 1 sixes (sum of players)",
    cell: "Prep Work!P36",
    namedRange: null,
    value: nzSaFoursSixes.team1Sixes.value,
    scope: "parameter" as const,
    notes: "SUM(P24:P34) — maps to GetTeamSixes() for home team",
  },
  {
    id: "team2-sixes",
    label: "Team 2 sixes (sum of players)",
    cell: "Prep Work!P57",
    namedRange: null,
    value: nzSaFoursSixes.team2Sixes.value,
    scope: "parameter" as const,
    notes: "SUM(P45:P55) — maps to GetTeamSixes() for away team",
  },
  {
    id: "match-sixes-total",
    label: "Match sixes (limited overs)",
    cell: "Prep Work!P36+P57",
    namedRange: null,
    value: nzSaFoursSixes.matchSixesLimited.value,
    scope: "parameter" as const,
    notes: "Team1 + team2 sixes before PM Publication I53 adjust",
  },
  {
    id: "match-extras-total",
    label: "Match extras (limited overs)",
    cell: "Prep Work!M35+M56",
    namedRange: null,
    value: nzSaTeamInningsTotals.limitedOversMatchTotals.extras,
    scope: "parameter" as const,
    notes: "M35+M56 ExtrasPrediction — maps to MatchExtras before I58 adjust",
  },
  {
    id: "match-wickets-total",
    label: "Match wickets (limited overs)",
    cell: "Prep Work!U38+U59",
    namedRange: null,
    value: nzSaTeamInningsTotals.limitedOversMatchTotals.wickets,
    scope: "parameter" as const,
    notes: "Team wickets totals — maps to MatchWickets before I59 adjust",
  },
  {
    id: "match-wides-total",
    label: "Match wides (limited overs)",
    cell: "Prep Work!W38+W59",
    namedRange: null,
    value: nzSaTeamInningsTotals.limitedOversMatchTotals.wides,
    scope: "parameter" as const,
    notes: "Team wides totals — maps to MatchWides before I57 adjust",
  },
  {
    id: "match-run-outs-total",
    label: "Match run outs (limited overs)",
    cell: "Prep Work!U36+U57",
    namedRange: null,
    value: nzSaTeamInningsTotals.limitedOversMatchTotals.runOuts,
    scope: "parameter" as const,
    notes: "Team run outs — maps to MatchRunOuts before I54 adjust (÷10 in Lambda)",
  },
  {
    id: "rabbit-runs-expectation",
    label: "Rabbit runs expectation",
    cell: "Prep Work!Y10",
    namedRange: null,
    value: 0.965104517869184,
    scope: "parameter" as const,
    notes: "T10 Rabbit runs — column Y All blend",
  },
  {
    id: "match-max-over-expectation",
    label: "Match max over expectation",
    cell: "Prep Work!Z3",
    namedRange: null,
    value: 20.278758788504465,
    scope: "parameter" as const,
    notes: "T3 Match Max Over model column",
  },
  {
    id: "match-ducks-total",
    label: "Match ducks (limited overs)",
    cell: "Prep Work!O16×2",
    namedRange: null,
    value: 1.3149022252191505,
    scope: "parameter" as const,
    notes: "K16:P16 O16 per innings × 2 teams — Round(1.31−0.8)+0.5 = PM F56 line 1.5",
  },
];

export const workbookSheets = {
  preMatch: [
    "Prep Work",
    "PM Publication",
    "PM Pricing",
    "PMO Data",
    "PMO Deliveries",
    "PM Book Transfer",
  ],
  inPlay: ["UI", "Scoring", "Pricing", "Input", "Scorecard"],
};
